// Generated by `uitive generate sources` from Acme Payments API 2026-10-10 (openapi.json).
// Keep choices in adapters/acme-payments/curation.json: regenerating replaces this file.
import { field, source } from '@plurid/uitive-core';
import type { RestAction, RestSource } from '@plurid/uitive-core';
import { z } from 'zod';

/** The base URL the description names; bindings may use another. */
export const server = 'https://api.acme-payments.example';

export const sources = {
  charges: source({
    label: 'Payments',
    description: 'Attempts to take a payment, one per charge: amount, status, customer and card.',
    keywords: ['charge', 'transaction', 'sale'],
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      /** Amount the payment asked for, in the currency's smallest unit (cents for euros). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Amount refunded, in the currency's smallest unit (cents for euros). */
      amount_refunded: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      status: field.enum(['failed', 'succeeded']),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      customer: field.ref('customers').nullable(),
      /** What the payment was for. */
      description: z.string().nullable(),
      /** Where the receipt went. */
      receipt_email: z.string().nullable(),
      refunded: z.boolean(),
      disputed: z.boolean(),
      payment_intent: z.string().nullable(),
      failure_message: z.string().nullable(),
      failure_code: z.string().nullable(),
      captured: z.boolean(),
      card_brand: z.string().nullable(),
      card_last4: z.string().nullable(),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        customer: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  customers: source({
    label: 'Customers',
    description: 'Someone who pays the business.',
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      name: z.string().nullable(),
      email: z.string().nullable(),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Credit or debt carried to the next invoice, in the currency's smallest unit. */
      balance: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      delinquent: z.boolean(),
      description: z.string().nullable(),
      phone: z.string().nullable(),
    }),
    key: 'id',
    title: 'name',
    summary: ['name', 'balance', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  disputes: source({
    label: 'Disputes',
    description: "A customer questioning a payment with their card's issuer.",
    keywords: ['chargeback'],
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      /** Amount disputed, in the currency's smallest unit (cents for euros). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      status: field.enum(['needs_response', 'under_review', 'won', 'lost']),
      reason: z.string(),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      charge: field.ref('charges'),
      payment_intent: z.string().nullable(),
      is_charge_refundable: z.boolean(),
    }),
    key: 'id',
    summary: ['id', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        charge: ['eq'],
        payment_intent: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  payouts: source({
    label: 'Payouts',
    description: "Money sent from the balance to the business's bank account.",
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      /** Amount paid out, in the currency's smallest unit (cents for euros). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      status: field.enum(['paid', 'pending', 'in_transit', 'canceled', 'failed']),
      /** When the payout arrives, in seconds since the Unix epoch. */
      arrival_date: field.time({ unit: 's' }),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      method: field.enum(['standard', 'instant']),
      type: field.enum(['bank_account', 'card']),
      description: z.string().nullable(),
      failure_message: z.string().nullable(),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        status: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  refunds: source({
    label: 'Refunds',
    description: 'Money given back for a payment.',
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      /** Amount refunded, in the currency's smallest unit (cents for euros). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      status: field.enum(['pending', 'succeeded', 'failed', 'canceled']),
      reason: z.string().nullable(),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      charge: field.ref('charges'),
      payment_intent: z.string().nullable(),
    }),
    key: 'id',
    summary: ['id', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        charge: ['eq'],
        payment_intent: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  'balance-transactions': source({
    label: 'Balance transactions',
    description: 'Money moving in or out of the balance, with its fee.',
    keywords: ['fee', 'net', 'balance'],
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      /** Gross amount, in the currency's smallest unit (cents for euros). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Fee, in the currency's smallest unit (cents for euros). */
      fee: field.money({ currency: 'currency', minor: true }),
      /** Net amount, in the currency's smallest unit (cents for euros). */
      net: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      type: field.enum(['charge', 'refund', 'payout', 'adjustment']),
      status: field.enum(['available', 'pending']),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** When the funds become available, in seconds since the Unix epoch. */
      available_on: field.time({ unit: 's' }),
      description: z.string().nullable(),
      reporting_category: z.string(),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  invoices: source({
    label: 'Invoices',
    description: 'A statement of what a customer owes.',
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      /** Amount due, in the currency's smallest unit (cents for euros). */
      amount_due: field.money({ currency: 'currency', minor: true }),
      /** Amount paid, in the currency's smallest unit (cents for euros). */
      amount_paid: field.money({ currency: 'currency', minor: true }),
      /** Amount left to pay, in the currency's smallest unit (cents for euros). */
      amount_remaining: field.money({ currency: 'currency', minor: true }),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      status: field.enum(['draft', 'open', 'paid', 'uncollectible', 'void']),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** When payment is due, in seconds since the Unix epoch. */
      due_date: field.time({ unit: 's' }).nullable(),
      customer: field.ref('customers'),
      number: z.string().nullable(),
      customer_email: z.string().nullable(),
    }),
    key: 'id',
    title: 'number',
    summary: ['number', 'amount_due', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        customer: ['eq'],
        status: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  subscriptions: source({
    label: 'Subscriptions',
    description: 'A customer paying again and again for a plan.',
    row: z.object({
      /** Unique identifier for the object. */
      id: z.string(),
      status: field.enum(['active', 'past_due', 'canceled', 'incomplete', 'trialing', 'unpaid']),
      /** When the object was created, in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      customer: field.ref('customers'),
      /** Three-letter ISO currency code, in lowercase. */
      currency: z.string(),
      cancel_at_period_end: z.boolean(),
      description: z.string().nullable(),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        customer: ['eq'],
        status: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
};

export const actions = {};

/** How each source and action maps to the API, for `restFetch` and `restPerform`. */
export const endpoints: {
  sources: Record<string, RestSource>;
  actions: Record<string, RestAction>;
} = {
  sources: {
    charges: {
      path: '/v1/charges',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'customer:eq': 'customer',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/charges/{charge}',
      },
      pick: {
        card_brand: '/payment_method_details/card/brand',
        card_last4: '/payment_method_details/card/last4',
      },
    },
    customers: {
      path: '/v1/customers',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/customers/{customer}',
      },
    },
    disputes: {
      path: '/v1/disputes',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'charge:eq': 'charge',
        'payment_intent:eq': 'payment_intent',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/disputes/{dispute}',
      },
    },
    payouts: {
      path: '/v1/payouts',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'status:eq': 'status',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/payouts/{payout}',
      },
    },
    refunds: {
      path: '/v1/refunds',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'charge:eq': 'charge',
        'payment_intent:eq': 'payment_intent',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/refunds/{refund}',
      },
    },
    'balance-transactions': {
      path: '/v1/balance_transactions',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/balance_transactions/{balance_transaction}',
      },
    },
    invoices: {
      path: '/v1/invoices',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'customer:eq': 'customer',
        'status:eq': 'status',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/invoices/{invoice}',
      },
    },
    subscriptions: {
      path: '/v1/subscriptions',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'customer:eq': 'customer',
        'status:eq': 'status',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/subscriptions/{subscription}',
      },
    },
  },
  actions: {},
};
