// Generated by `aptuitive generate sources` from Stripe API 2026-09-30.endive (stripe.json).
// Keep choices in adapters/stripe/curation.json: regenerating replaces this file.
import { field, source } from '@plurid/aptuitive-core';
import type { RestAction, RestSource } from '@plurid/aptuitive-core';
import { z } from 'zod';

/** The base URL the description names; bindings may use another. */
export const server = 'https://api.stripe.com';

export const sources = {
  'balance-transactions': source({
    label: 'Balance transactions',
    description:
      'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: Balance transaction types',
    keywords: ['fee', 'net', 'balance'],
    row: z.object({
      /** Gross amount of this transaction (in cents (or local equivalent)). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** The date that the transaction's net funds become available in the Stripe balance. */
      available_on: field.time({ unit: 's' }),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** An arbitrary string attached to the object. Often useful for displaying to users. */
      description: z.string().nullable(),
      /** Fees (in cents (or local equivalent)) paid for this transaction. Represented as a positive integer when assessed. */
      fee: field.money({ currency: 'currency', minor: true }),
      /** Unique identifier for the object. */
      id: z.string(),
      /** Net impact to a Stripe balance (in cents (or local equivalent)). */
      net: field.money({ currency: 'currency', minor: true }),
      /** Learn more about how reporting categories can help you understand balance transactions from an accounting perspective. */
      reporting_category: z.string(),
      /** The transaction's net funds status in the Stripe balance, which are either available or pending. */
      status: z.string(),
      /** Transaction type: tax_fund, adjustment, advance, advance_funding, anticipation_repayment, application_fee, application_fee_refund, charge, climate_order_purc... */
      type: field.enum([
        'adjustment',
        'advance',
        'advance_funding',
        'anticipation_repayment',
        'application_fee',
        'application_fee_refund',
        'charge',
        'climate_order_purchase',
        'climate_order_refund',
        'connect_collection_transfer',
        'contribution',
        'fee_credit_funding',
        'inbound_transfer',
        'inbound_transfer_reversal',
        'issuing_authorization_hold',
        'issuing_authorization_release',
        'issuing_dispute',
        'issuing_dispute_provisional_credit',
        'issuing_dispute_provisional_credit_reversal',
        'issuing_transaction',
        'obligation_outbound',
        'obligation_reversal_inbound',
        'payment',
        'payment_failure_refund',
        'payment_network_reserve_hold',
        'payment_network_reserve_release',
        'payment_refund',
        'payment_reversal',
        'payment_unreconciled',
        'payout',
        'payout_cancel',
        'payout_failure',
        'payout_minimum_balance_hold',
        'payout_minimum_balance_release',
        'refund',
        'refund_failure',
        'reserve_hold',
        'reserve_release',
        'reserve_transaction',
        'reserved_funds',
        'stripe_balance_payment_debit',
        'stripe_balance_payment_debit_reversal',
        'stripe_fee',
        'stripe_fx_fee',
        'tax_fee',
        'tax_fund',
        'topup',
        'topup_reversal',
        'transfer',
        'transfer_cancel',
        'transfer_failure',
        'transfer_refund',
      ]),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'amount', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        currency: ['eq'],
        type: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  charges: source({
    label: 'Payments',
    description:
      'Attempts to move money into the account, one per charge: amount, status, customer and card.',
    keywords: ['charge', 'transaction', 'sale'],
    row: z.object({
      /** Amount intended to be collected by this payment. */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Amount in cents (or local equivalent) refunded (can be less than the amount attribute on the charge if a partial refund was issued). */
      amount_refunded: field.money({ currency: 'currency', minor: true }),
      /** If the charge was created without capturing, this Boolean represents whether it is still uncaptured or has since been captured. */
      captured: z.boolean(),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** ID of the customer this charge is for if one exists. */
      customer: field.ref('customers').nullable(),
      /** An arbitrary string attached to the object. Often useful for displaying to users. */
      description: z.string().nullable(),
      /** Whether the charge has been disputed. */
      disputed: z.boolean(),
      /** Error code explaining reason for charge failure if available (see the errors section for a list of codes). */
      failure_code: z.string().nullable(),
      /** Message to user further explaining reason for charge failure if available. */
      failure_message: z.string().nullable(),
      /** Unique identifier for the object. */
      id: z.string(),
      /** ID of the PaymentIntent associated with this charge, if one exists. */
      payment_intent: z.string().nullable(),
      /** This is the email address that the receipt for this charge was sent to. */
      receipt_email: z.string().nullable(),
      /** Whether the charge has been fully refunded. If the charge is only partially refunded, this attribute will still be false. */
      refunded: z.boolean(),
      /** The status of the payment is either succeeded, pending, or failed. */
      status: field.enum(['failed', 'pending', 'succeeded']),
      /** Card brand. Can be amex, cartes_bancaires, diners, discover, eftpos_au, jcb, link, mastercard, unionpay, visa or unknown. */
      card_brand: z.string().nullable(),
      /** The last four digits of the card. */
      card_last4: z.string().nullable(),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        customer: ['eq'],
        payment_intent: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  customers: source({
    label: 'Customers',
    description:
      'This object represents a customer of your business. Use it to create recurring charges, save payment and contact information, and track payments that belong to the same customer.',
    row: z.object({
      /** The current balance, if any, that's stored on the customer in their default currency. If negative, the customer has credit to apply to their next invoice. */
      balance: field.money({ currency: 'currency', minor: true }),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO code for the currency the customer can be charged in for recurring billing purposes. */
      currency: z.string().nullable(),
      /** Tracks the most recent state change on any invoice belonging to the customer. */
      delinquent: z.boolean().nullable(),
      /** An arbitrary string attached to the object. Often useful for displaying to users. */
      description: z.string().nullable(),
      /** The customer's email address. */
      email: z.string().nullable(),
      /** Unique identifier for the object. */
      id: z.string(),
      /** The customer's full name or business name. */
      name: z.string().nullable(),
      /** The customer's phone number. */
      phone: z.string().nullable(),
    }),
    key: 'id',
    title: 'name',
    summary: ['name', 'balance', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        email: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  disputes: source({
    label: 'Disputes',
    description:
      'A dispute occurs when a customer questions your charge with their card issuer. When this happens, you have the opportunity to respond to the dispute with evidence that shows that the charge is legitimate. Related guide: Disputes and fraud',
    keywords: ['chargeback'],
    row: z.object({
      /** Disputed amount. Usually the amount of the charge, but it can differ (usually because of currency fluctuation or because only part of the order is disputed). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** ID of the charge that's disputed. */
      charge: field.ref('charges'),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** Unique identifier for the object. */
      id: z.string(),
      /** If true, it's still possible to refund the disputed payment. */
      is_charge_refundable: z.boolean(),
      /** ID of the PaymentIntent that's disputed. */
      payment_intent: z.string().nullable(),
      /** Reason given by cardholder for dispute. */
      reason: z.string(),
      /** The current status of a dispute. */
      status: field.enum([
        'lost',
        'needs_response',
        'prevented',
        'under_review',
        'warning_closed',
        'warning_needs_response',
        'warning_under_review',
        'won',
      ]),
    }),
    key: 'id',
    summary: ['id', 'amount', 'status', 'created'],
    capabilities: {
      filter: {
        charge: ['eq'],
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        payment_intent: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  invoices: source({
    label: 'Invoices',
    description:
      'Invoices are statements of amounts owed by a customer, and are either generated one-off, or generated periodically from a subscription.',
    row: z.object({
      /** Final amount due at this time for this invoice. */
      amount_due: field.money({ currency: 'currency', minor: true }),
      /** The amount, in cents (or local equivalent), that was paid. */
      amount_paid: field.money({ currency: 'currency', minor: true }),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** The ID of the customer to bill. */
      customer: field.ref('customers'),
      /** The customer's email. Until the invoice is finalized, this field will equal customer.email. Once the invoice is finalized, this field will no longer be updated. */
      customer_email: z.string().nullable(),
      /** The date on which payment for this invoice is due. This value will be null for invoices where collection_method=charge_automatically. */
      due_date: field.time({ unit: 's' }).nullable(),
      /** Unique identifier for the object. For preview invoices created using the create preview endpoint, this id will be prefixed with upcoming_in. */
      id: z.string(),
      /** A unique, identifying string that appears on emails sent to the customer for this invoice. */
      number: z.string().nullable(),
      /** The status of the invoice, one of draft, open, paid, uncollectible, or void. Learn more */
      status: field.enum(['draft', 'open', 'paid', 'uncollectible', 'void']).nullable(),
      /** The difference between amount_due and amount_paid, in cents (or local equivalent). */
      amount_remaining: field.money({ currency: 'currency', minor: true }),
    }),
    key: 'id',
    title: 'number',
    summary: ['number', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        customer: ['eq'],
        due_date: ['gt', 'gte', 'lt', 'lte', 'between'],
        status: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  payouts: source({
    label: 'Payouts',
    description:
      'A Payout object is created when you receive funds from Stripe, or when you initiate a payout to either a bank account or debit card of a connected Stripe account. You can retrieve individual payouts, and list all payouts.',
    row: z.object({
      /** The amount (in cents (or local equivalent)) that transfers to your bank account or debit card. */
      amount: field.money({ currency: 'currency', minor: true }),
      /** Date that you can expect the payout to arrive in the bank. This factors in delays to account for weekends or bank holidays. */
      arrival_date: field.time({ unit: 's' }),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** An arbitrary string attached to the object. Often useful for displaying to users. */
      description: z.string().nullable(),
      /** Message that provides the reason for a payout failure, if available. */
      failure_message: z.string().nullable(),
      /** Unique identifier for the object. */
      id: z.string(),
      /** The method used to send this payout, which can be standard or instant. instant is supported for payouts to debit cards and bank accounts in certain countries. */
      method: z.string(),
      /** Current status of the payout: paid, pending, in_transit, canceled or failed. A payout is pending until it's submitted to the bank, when it becomes in_transit. */
      status: z.string(),
      /** Can be bank_account or card. */
      type: field.enum(['bank_account', 'card']),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'amount', 'created'],
    capabilities: {
      filter: {
        arrival_date: ['gt', 'gte', 'lt', 'lte', 'between'],
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        status: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  refunds: source({
    label: 'Refunds',
    description:
      "Refund objects allow you to refund a previously created charge that isn't refunded yet. Funds are refunded to the credit or debit card that's initially charged. Related guide: Refunds",
    row: z.object({
      /** Amount, in cents (or local equivalent). */
      amount: field.money({ currency: 'currency', minor: true }),
      /** ID of the charge that's refunded. */
      charge: field.ref('charges').nullable(),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** Unique identifier for the object. */
      id: z.string(),
      /** ID of the PaymentIntent that's refunded. */
      payment_intent: z.string().nullable(),
      /** Reason for the refund, which is either user-provided (duplicate, fraudulent, or requested_by_customer) or generated by Stripe internally (expired_uncaptured_... */
      reason: field
        .enum(['duplicate', 'expired_uncaptured_charge', 'fraudulent', 'requested_by_customer'])
        .nullable(),
      /** Status of the refund. This can be pending, requires_action, succeeded, failed, or canceled. Learn more about failed refunds. */
      status: z.string().nullable(),
    }),
    key: 'id',
    summary: ['amount', 'created'],
    capabilities: {
      filter: {
        charge: ['eq'],
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        payment_intent: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
  subscriptions: source({
    label: 'Subscriptions',
    description:
      'Subscriptions allow you to charge a customer on a recurring basis. Related guide: Creating subscriptions',
    row: z.object({
      /** Whether this subscription will (if status=active) or did (if status=canceled) cancel at the end of the current billing period. */
      cancel_at_period_end: z.boolean(),
      /** Time at which the object was created. Measured in seconds since the Unix epoch. */
      created: field.time({ unit: 's' }),
      /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
      currency: z.string(),
      /** ID of the customer who owns the subscription. */
      customer: field.ref('customers'),
      /** The subscription's description, meant to be displayable to the customer. */
      description: z.string().nullable(),
      /** Unique identifier for the object. */
      id: z.string(),
      /** Possible values are incomplete, incomplete_expired, trialing, active, past_due, canceled, unpaid, or paused. */
      status: field.enum([
        'active',
        'canceled',
        'incomplete',
        'incomplete_expired',
        'past_due',
        'paused',
        'trialing',
        'unpaid',
      ]),
    }),
    key: 'id',
    title: 'description',
    summary: ['description', 'status', 'created'],
    capabilities: {
      filter: {
        created: ['gt', 'gte', 'lt', 'lte', 'between'],
        customer: ['eq'],
        status: ['eq'],
        id: ['eq', 'in'],
      },
      sort: [],
      search: false,
      pagination: 'cursor',
    },
  }),
};

export const actions = {};

/** How each source and action maps to the API, for `restFetch` and `restPerform`. */
export const endpoints = {
  sources: {
    'balance-transactions': {
      path: '/v1/balance_transactions',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'currency:eq': 'currency',
        'source:eq': 'source',
        'type:eq': 'type',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/balance_transactions/{id}',
      },
    },
    charges: {
      path: '/v1/charges',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'customer:eq': 'customer',
        'payment_intent:eq': 'payment_intent',
        'transfer_group:eq': 'transfer_group',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      pick: {
        card_brand: '/payment_method_details/card/brand',
        card_last4: '/payment_method_details/card/last4',
      },
      item: {
        path: '/v1/charges/{charge}',
      },
    },
    customers: {
      path: '/v1/customers',
      rows: '/data',
      filters: {
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'email:eq': 'email',
        'test_clock:eq': 'test_clock',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/customers/{customer}',
      },
    },
    disputes: {
      path: '/v1/disputes',
      rows: '/data',
      filters: {
        'charge:eq': 'charge',
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'payment_intent:eq': 'payment_intent',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/disputes/{dispute}',
      },
    },
    invoices: {
      path: '/v1/invoices',
      rows: '/data',
      filters: {
        'collection_method:eq': 'collection_method',
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'customer:eq': 'customer',
        'customer_account:eq': 'customer_account',
        'due_date:gt': 'due_date[gt]',
        'due_date:gte': 'due_date[gte]',
        'due_date:lt': 'due_date[lt]',
        'due_date:lte': 'due_date[lte]',
        'status:eq': 'status',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/invoices/{invoice}',
      },
    },
    payouts: {
      path: '/v1/payouts',
      rows: '/data',
      filters: {
        'arrival_date:gt': 'arrival_date[gt]',
        'arrival_date:gte': 'arrival_date[gte]',
        'arrival_date:lt': 'arrival_date[lt]',
        'arrival_date:lte': 'arrival_date[lte]',
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'destination:eq': 'destination',
        'status:eq': 'status',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/payouts/{payout}',
      },
    },
    refunds: {
      path: '/v1/refunds',
      rows: '/data',
      filters: {
        'charge:eq': 'charge',
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'payment_intent:eq': 'payment_intent',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/refunds/{refund}',
      },
    },
    subscriptions: {
      path: '/v1/subscriptions',
      rows: '/data',
      filters: {
        'collection_method:eq': 'collection_method',
        'created:gt': 'created[gt]',
        'created:gte': 'created[gte]',
        'created:lt': 'created[lt]',
        'created:lte': 'created[lte]',
        'customer:eq': 'customer',
        'customer_account:eq': 'customer_account',
        'status:eq': 'status',
        'test_clock:eq': 'test_clock',
      },
      limit: 'limit',
      pagination: {
        kind: 'cursor',
        param: 'starting_after',
      },
      more: '/has_more',
      item: {
        path: '/v1/subscriptions/{subscription_exposed_id}',
      },
    },
  },
  actions: {},
} satisfies {
  sources: Record<string, RestSource>;
  actions: Record<string, RestAction>;
};
