// A fictional cloud platform. Every name is generic on purpose: the point is the shape of a
// large console (hundreds of services, each with a dozen actions), not any real vendor.

/** What you can do on a service page. */
export const verbs = {
  create: ['Create', 'Create a new resource of this kind'],
  deploy: ['Deploy', 'Release a new version'],
  start: ['Start', 'Start stopped resources'],
  stop: ['Stop', 'Stop running resources'],
  restart: ['Restart', 'Restart resources'],
  scale: ['Scale', 'Change capacity or instance count'],
  logs: ['Logs', 'Read the logs this service writes'],
  metrics: ['Metrics', 'Charts of usage and performance'],
  alarms: ['Alarms', 'Alerts when a metric crosses a threshold'],
  settings: ['Settings', 'Configuration of this service'],
  permissions: ['Permissions', 'Who may use or change these resources'],
  versions: ['Versions', 'Earlier versions and their history'],
  rollback: ['Roll back', 'Return to an earlier version'],
  connect: ['Connect', 'Connection details and credentials'],
  query: ['Query', 'Run a query against the data'],
  upload: ['Upload', 'Upload files'],
  download: ['Download', 'Download files or exports'],
  share: ['Share', 'Share with another account or person'],
  backups: ['Backups', 'Scheduled and manual backups'],
  restore: ['Restore', 'Restore from a backup or snapshot'],
  invalidate: ['Clear cache', 'Make edge locations fetch fresh content'],
  rotate: ['Rotate', 'Replace keys, secrets or certificates'],
  schedule: ['Schedule', 'Run on a schedule'],
  triggers: ['Triggers', 'Events that start this resource'],
  environment: ['Environment', 'Variables and runtime configuration'],
  endpoints: ['Endpoints', 'Addresses this service is reachable at'],
  tags: ['Tags', 'Labels for organising and billing'],
  costs: ['Costs', 'What this service costs you'],
  export: ['Export', 'Export data or reports'],
  test: ['Test', 'Send a test request or event'],
  migrate: ['Migrate', 'Move resources between regions or tiers'],
  delete: ['Delete', 'Delete resources'],
} as const;

export type Verb = keyof typeof verbs;

const common: Verb[] = ['settings', 'permissions', 'metrics', 'tags', 'costs', 'delete'];
const templates: Record<string, Verb[]> = {
  compute: [
    'create',
    'deploy',
    'start',
    'stop',
    'restart',
    'scale',
    'logs',
    'alarms',
    'versions',
    'rollback',
    'connect',
    'environment',
    ...common,
  ],
  storage: [
    'create',
    'upload',
    'download',
    'share',
    'versions',
    'backups',
    'restore',
    'migrate',
    ...common,
  ],
  databases: [
    'create',
    'connect',
    'query',
    'scale',
    'backups',
    'restore',
    'logs',
    'alarms',
    'versions',
    'migrate',
    'export',
    ...common,
  ],
  networking: ['create', 'endpoints', 'logs', 'alarms', 'test', 'invalidate', ...common],
  security: ['create', 'rotate', 'logs', 'alarms', 'export', 'test', ...common],
  operations: ['create', 'logs', 'alarms', 'schedule', 'export', 'test', 'share', ...common],
  developer: [
    'create',
    'deploy',
    'versions',
    'rollback',
    'triggers',
    'environment',
    'logs',
    'test',
    'endpoints',
    ...common,
  ],
  ai: [
    'create',
    'deploy',
    'scale',
    'stop',
    'logs',
    'alarms',
    'versions',
    'endpoints',
    'test',
    'upload',
    ...common,
  ],
  analytics: [
    'create',
    'query',
    'schedule',
    'scale',
    'logs',
    'export',
    'share',
    'connect',
    ...common,
  ],
  integration: ['create', 'test', 'triggers', 'logs', 'alarms', 'endpoints', 'schedule', ...common],
  media: ['create', 'upload', 'download', 'logs', 'endpoints', 'test', ...common],
  iot: ['create', 'deploy', 'logs', 'alarms', 'triggers', 'versions', 'test', ...common],
  business: ['create', 'connect', 'share', 'export', 'logs', ...common],
  migration: ['create', 'migrate', 'logs', 'schedule', 'test', ...common],
  governance: ['create', 'export', 'logs', 'schedule', 'share', ...common],
  billing: ['export', 'download', 'share', 'schedule', 'settings', 'permissions', 'costs'],
  desktops: ['create', 'start', 'stop', 'restart', 'scale', 'connect', 'logs', ...common],
  frontier: ['create', 'start', 'stop', 'scale', 'logs', 'test', ...common],
  support: ['create', 'share', 'export', 'settings'],
  frontend: [
    'create',
    'deploy',
    'versions',
    'rollback',
    'environment',
    'logs',
    'endpoints',
    'test',
    'invalidate',
    ...common,
  ],
};

type Entry = readonly [id: string, label: string, description: string];

export const categories: readonly { id: string; label: string; services: readonly Entry[] }[] = [
  {
    id: 'compute',
    label: 'Compute',
    services: [
      [
        'virtual-machines',
        'Virtual machines',
        'Resizable servers with the operating system of your choice',
      ],
      ['containers', 'Container service', 'Run containers without managing servers'],
      ['kubernetes', 'Kubernetes clusters', 'A managed Kubernetes control plane and node pools'],
      ['functions', 'Functions', 'Run code in response to events, paying per call'],
      ['batch', 'Batch jobs', 'Queue and run large batches of compute work'],
      ['spare-capacity', 'Spare capacity', 'Discounted machines that may be interrupted'],
      ['gpu-machines', 'GPU machines', 'Servers with accelerators for training and rendering'],
      ['app-platform', 'App platform', 'Deploy web applications from a repository with no setup'],
      ['edge-compute', 'Edge compute', 'Run code in locations close to your users'],
      ['autoscaling', 'Autoscaling groups', 'Grow and shrink fleets of machines automatically'],
      ['dedicated-hosts', 'Dedicated hosts', 'Physical servers reserved for your workloads'],
    ],
  },
  {
    id: 'storage',
    label: 'Storage',
    services: [
      ['object-storage', 'Object storage', 'Store and serve files of any size'],
      ['block-volumes', 'Block volumes', 'Disks you attach to virtual machines'],
      ['file-shares', 'File shares', 'Network file systems shared by many machines'],
      ['archive', 'Archive storage', 'Very cheap storage for data you rarely read'],
      ['backup-vault', 'Backup vault', 'Scheduled, policy-driven backups of your resources'],
      ['storage-transfer', 'Storage transfer', 'Move large datasets between locations'],
      [
        'offline-transfer',
        'Offline data shipping',
        'Ship physical drives to import terabytes at once',
      ],
      [
        'storage-gateway',
        'Storage gateway',
        'Connect servers in your own building to cloud storage',
      ],
      ['disk-snapshots', 'Disk snapshots', 'Point-in-time copies of volumes and disks'],
      ['static-sites', 'Static website hosting', 'Serve a static website straight from storage'],
    ],
  },
  {
    id: 'databases',
    label: 'Databases',
    services: [
      [
        'postgres',
        'Managed PostgreSQL',
        'PostgreSQL databases with backups and failover handled for you',
      ],
      ['mysql', 'Managed MySQL', 'MySQL databases with backups and failover handled for you'],
      ['document-db', 'Document database', 'Store and query JSON documents at any scale'],
      ['key-value', 'Key-value store', 'Single-digit-millisecond reads and writes by key'],
      ['cache', 'In-memory cache', 'A managed cache to make applications faster'],
      ['graph-db', 'Graph database', 'Store and traverse highly connected data'],
      ['time-series', 'Time-series database', 'Metrics and events indexed by time'],
      ['ledger-db', 'Ledger database', 'An append-only, verifiable history of changes'],
      ['search-service', 'Search service', 'Full-text search over your own content'],
      [
        'database-migration',
        'Database migration',
        'Move databases into the cloud with little downtime',
      ],
      ['vector-db', 'Vector database', 'Similarity search over embeddings'],
    ],
  },
  {
    id: 'networking',
    label: 'Networking',
    services: [
      ['networks', 'Virtual networks', 'Private networks for your resources'],
      ['load-balancers', 'Load balancers', 'Spread traffic across healthy servers'],
      ['cdn', 'Content delivery network', 'Cache and serve content from locations worldwide'],
      ['dns', 'DNS', 'Point domain names at your services'],
      ['domains', 'Domain registration', 'Buy and renew domain names'],
      ['vpn', 'VPN gateways', 'Connect your office network to the cloud securely'],
      ['private-links', 'Private links', 'Reach services without crossing the public internet'],
      ['nat', 'NAT gateways', 'Let private resources reach the internet'],
      ['network-firewall', 'Network firewall', 'Filter traffic between networks'],
      ['traffic-manager', 'Traffic manager', 'Route users to the nearest healthy region'],
      ['static-ips', 'Static IP addresses', 'Addresses that stay the same across restarts'],
    ],
  },
  {
    id: 'security',
    label: 'Security and identity',
    services: [
      ['iam', 'Identity and access', 'Users, roles and what each may do'],
      ['secrets', 'Secrets manager', 'Store and rotate passwords and API keys'],
      ['key-management', 'Key management', 'Encryption keys and signing'],
      ['certificates', 'Certificates', 'Issue and renew TLS certificates for your domains'],
      ['web-firewall', 'Web application firewall', 'Block common attacks on web applications'],
      ['ddos-protection', 'DDoS protection', 'Absorb floods of malicious traffic'],
      ['security-centre', 'Security centre', 'Findings and posture across your account'],
      ['audit-log', 'Audit log', 'Who did what, and when'],
      ['compliance', 'Compliance reports', 'Reports for auditors and regulators'],
      ['single-sign-on', 'Single sign-on', 'One login for your team across tools'],
    ],
  },
  {
    id: 'operations',
    label: 'Monitoring and operations',
    services: [
      ['metrics-explorer', 'Metrics explorer', 'Charts and dashboards of resource metrics'],
      ['log-explorer', 'Log explorer', 'Search and analyse logs from every service'],
      ['alerting', 'Alerting', 'Notify people when something breaks'],
      ['tracing', 'Tracing', 'Follow requests across services'],
      ['uptime-checks', 'Uptime checks', 'Probe your endpoints from around the world'],
      ['incident-manager', 'Incident manager', 'Coordinate responses to outages'],
      ['status-pages', 'Status pages', 'Tell your customers about incidents'],
      ['dashboards', 'Dashboards', 'Build views that combine metrics and logs'],
      ['synthetic-tests', 'Synthetic tests', 'Scripted journeys that run on a schedule'],
      ['profiler', 'Profiler', 'See where your code spends its time'],
    ],
  },
  {
    id: 'developer',
    label: 'Developer tools',
    services: [
      ['repositories', 'Code repositories', 'Private Git repositories'],
      ['pipelines', 'Build pipelines', 'Build, test and release on every change'],
      ['artifacts', 'Artifact registry', 'Packages and build outputs in one place'],
      ['container-registry', 'Container registry', 'Store and scan container images'],
      ['cloud-shell', 'Cloud shell', 'A terminal in the browser with tools installed'],
      ['online-ide', 'Online IDE', 'Write and run code in the browser'],
      ['api-gateway', 'API gateway', 'Publish, secure and meter APIs'],
      [
        'templates',
        'Infrastructure templates',
        'Describe resources as code and deploy them together',
      ],
      ['feature-flags', 'Feature flags', 'Turn features on for some users first'],
      ['device-lab', 'Device test lab', 'Test apps on real phones and tablets'],
    ],
  },
  {
    id: 'ai',
    label: 'AI and machine learning',
    services: [
      ['model-hosting', 'Model hosting', 'Serve trained models behind an endpoint'],
      ['training', 'Model training', 'Train models on managed clusters'],
      ['notebooks', 'Notebooks', 'Interactive notebooks for data science'],
      ['datasets', 'Datasets', 'Versioned datasets for training and evaluation'],
      ['labelling', 'Data labelling', 'Label images, text and audio with a workforce'],
      ['speech', 'Speech to text', 'Transcribe audio and calls'],
      ['vision', 'Image analysis', 'Detect objects, text and faces in images'],
      ['translation', 'Translation', 'Translate text between languages'],
      ['language-models', 'Language models', 'Hosted large language models behind an API'],
      ['recommendations', 'Recommendations', 'Personalised recommendations from your data'],
      ['forecasting', 'Forecasting', 'Predict future values from time series'],
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    services: [
      ['warehouse', 'Data warehouse', 'Fast SQL analytics over large datasets'],
      ['data-lake', 'Data lake', 'Store raw data cheaply and query it in place'],
      ['etl', 'ETL jobs', 'Extract, transform and load data between systems'],
      ['stream-processing', 'Stream processing', 'Process events as they arrive'],
      ['serverless-query', 'Serverless query', 'Query files in storage with SQL, paying per query'],
      [
        'business-intelligence',
        'Business intelligence',
        'Dashboards and reports for the whole company',
      ],
      ['data-catalogue', 'Data catalogue', 'Find, document and govern datasets'],
      ['workflow-orchestration', 'Workflow orchestration', 'Schedule and monitor data pipelines'],
      ['spark', 'Spark clusters', 'Managed clusters for large-scale processing'],
      ['data-exchange', 'Data exchange', 'Share datasets with partners securely'],
    ],
  },
  {
    id: 'integration',
    label: 'Integration and messaging',
    services: [
      ['queues', 'Message queues', 'Decouple services with reliable queues'],
      ['topics', 'Publish/subscribe', 'Fan messages out to many subscribers'],
      ['event-bus', 'Event bus', 'Route events between applications'],
      ['email-sending', 'Email sending', 'Send transactional and marketing email'],
      ['sms', 'SMS and voice', 'Text messages and phone calls from your app'],
      ['push-notifications', 'Push notifications', 'Notifications to phones and browsers'],
      ['scheduler', 'Scheduler', 'Run tasks at set times'],
      ['state-machines', 'State machines', 'Coordinate multi-step workflows'],
      ['webhook-relay', 'Webhook relay', 'Receive and replay webhooks reliably'],
      ['message-broker', 'Managed message broker', 'Run a standard message broker without servers'],
    ],
  },
  {
    id: 'media',
    label: 'Media',
    services: [
      ['transcoding', 'Video transcoding', 'Convert video for every device'],
      ['live-streaming', 'Live streaming', 'Broadcast live video to large audiences'],
      ['media-library', 'Media library', 'Store and organise media assets'],
      ['image-resizing', 'Image resizing', 'Resize and optimise images on the fly'],
      ['audio-processing', 'Audio processing', 'Clean up and convert audio'],
      ['video-player', 'Video player', 'An embeddable player with analytics'],
      ['content-protection', 'Content protection', 'Keep premium video from being copied'],
    ],
  },
  {
    id: 'iot',
    label: 'Internet of things',
    services: [
      ['device-registry', 'Device registry', 'Register and authenticate devices'],
      ['iot-messaging', 'IoT messaging', 'Two-way messages between devices and the cloud'],
      ['digital-twins', 'Digital twins', 'Model buildings and machines in software'],
      ['edge-devices', 'Edge device manager', 'Run cloud workloads on your own hardware'],
      ['firmware-updates', 'Over-the-air updates', 'Update device firmware safely'],
      ['iot-analytics', 'IoT analytics', 'Analyse data from fleets of devices'],
    ],
  },
  {
    id: 'business',
    label: 'Business applications',
    services: [
      ['contact-centre', 'Contact centre', 'A cloud call centre for your support team'],
      ['chatbot-builder', 'Chatbot builder', 'Conversational bots for your website'],
      ['business-email', 'Business email', 'Email and calendars for your company'],
      ['video-meetings', 'Video meetings', 'Meetings and webinars'],
      ['forms', 'Forms', 'Collect answers and files from anyone'],
      ['document-signing', 'Document signing', 'Collect legally binding signatures'],
    ],
  },
  {
    id: 'migration',
    label: 'Migration and hybrid',
    services: [
      ['migration-hub', 'Migration hub', 'Track migrations across tools'],
      ['server-migration', 'Server migration', 'Copy running servers into the cloud'],
      ['app-discovery', 'Application discovery', 'Map what runs in your data centre'],
      ['hybrid-clusters', 'Hybrid clusters', 'Run one cluster across cloud and your own hardware'],
      ['on-premises-racks', 'On-premises racks', 'Cloud hardware delivered to your building'],
      [
        'virtualisation-migration',
        'Virtualisation migration',
        'Move virtualised workloads without rewriting them',
      ],
    ],
  },
  {
    id: 'governance',
    label: 'Management and governance',
    services: [
      ['organisations', 'Organisation accounts', 'Group accounts and apply rules to all of them'],
      ['policies', 'Policy rules', 'Prevent configurations you never want'],
      ['resource-groups', 'Resource groups', 'Manage related resources together'],
      ['tag-editor', 'Tag editor', 'Tag resources in bulk'],
      ['configuration-history', 'Configuration history', 'How every resource changed over time'],
      ['runbooks', 'Automation runbooks', 'Scripts that fix common problems'],
      ['service-catalogue', 'Service catalogue', 'Approved setups your teams can launch'],
      ['quotas', 'Quotas and limits', 'See and raise service limits'],
      ['advisor', 'Advisor', 'Recommendations to save money and reduce risk'],
    ],
  },
  {
    id: 'billing',
    label: 'Billing and cost',
    services: [
      ['billing', 'Billing', 'Invoices, payment methods and charges'],
      ['cost-explorer', 'Cost explorer', 'See where your money goes, by service and tag'],
      ['budgets', 'Budgets', 'Set spending limits and get warned before them'],
      ['cost-alerts', 'Cost anomaly alerts', 'Spot unusual spending early'],
      ['reserved-capacity', 'Reserved capacity', 'Commit to usage in exchange for discounts'],
      ['savings-plans', 'Savings plans', 'Flexible discounts for steady usage'],
      ['tax-settings', 'Tax settings', 'Tax registration and invoicing details'],
      ['usage-reports', 'Usage reports', 'Detailed usage exports for finance'],
      ['credits', 'Credits', 'Promotional and support credits'],
    ],
  },
  {
    id: 'desktops',
    label: 'End-user computing',
    services: [
      ['virtual-desktops', 'Virtual desktops', 'Desktops in the cloud for your staff'],
      ['app-streaming', 'App streaming', 'Stream desktop applications to a browser'],
      ['shared-drives', 'Shared drives', 'Shared folders for teams'],
      ['browser-isolation', 'Browser isolation', 'Browse risky sites safely'],
    ],
  },
  {
    id: 'frontier',
    label: 'Frontier technologies',
    services: [
      ['blockchain-nodes', 'Blockchain nodes', 'Run nodes for public and private ledgers'],
      ['quantum', 'Quantum computing', 'Run circuits on quantum hardware and simulators'],
      ['ground-stations', 'Satellite ground stations', 'Talk to satellites as a service'],
      ['robotics', 'Robotics simulation', 'Simulate and test robots in virtual worlds'],
      ['game-servers', 'Game servers', 'Host and scale multiplayer game sessions'],
      ['spatial-scenes', 'AR and VR scenes', 'Build and host 3D experiences'],
    ],
  },
  {
    id: 'support',
    label: 'Support',
    services: [
      ['support-cases', 'Support cases', 'Ask the support team for help'],
      ['service-health', 'Service health', 'Outages and maintenance that affect you'],
      ['documentation', 'Documentation', 'Guides and references for every service'],
      ['training-centre', 'Training', 'Courses and certifications'],
      ['marketplace', 'Marketplace', 'Software from partners, billed with your account'],
    ],
  },
  {
    id: 'frontend',
    label: 'Front end and mobile',
    services: [
      ['mobile-backend', 'Mobile backend', 'Data, files and functions for mobile apps'],
      ['user-sign-in', 'User sign-in', 'Sign-up, sign-in and accounts for your app’s users'],
      ['frontend-hosting', 'Front-end hosting', 'Build and host modern web front ends'],
      ['app-analytics', 'App analytics', 'Understand how people use your apps'],
      ['maps', 'Maps and location', 'Maps, places and routes'],
      ['graphql-api', 'GraphQL API', 'Managed GraphQL APIs over your data'],
    ],
  },
];

export interface Service {
  id: string;
  label: string;
  description: string;
  category: string;
  categoryLabel: string;
  verbs: readonly Verb[];
}

export const services: readonly Service[] = categories.flatMap((category) =>
  category.services.map(([id, label, description]) => ({
    id,
    label,
    description,
    category: category.id,
    categoryLabel: category.label,
    verbs: [...new Set(templates[category.id] ?? common)],
  })),
);

export const serviceIds = services.map((service) => service.id);
export const verbIds = Object.keys(verbs) as Verb[];
export const byId = new Map(services.map((service) => [service.id, service]));

/** Every action a person could take somewhere in the standard console. */
export const totalActions = services.reduce((sum, service) => sum + service.verbs.length, 0);
